name: Generate music metrics README every 1 hour

on:
  schedule:
    - cron: "0 * * * *"
  push:
  workflow_dispatch:

jobs:
  stuff:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8.5]


    steps:
      - uses: actions/checkout@v2

      - name: Get Spotify data
        uses: actions/setup-node@v1
        with:
          node-version: 14.6.0

      - run: yarn

      - run: node .
        env:
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
          SPOTIFY_REFRESH_TOKEN: ${{ secrets.SPOTIFY_REFRESH_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install plotly psutil requests
      
      - name: Generate plots
        run: |
          python figures/generate_feature_figures.py

      - name: Git
        run: |
          git add .
          git config --global user.name "GitHub Action"
          git config --global user.email "denisvashchenko@gmail.com"
          git diff --quiet && git diff --staged --quiet || git commit -am "Automated README update"

      - name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
